# Python  Practice Question (07-02-2026)

In [ ]:
# Question 01
for i in range(1, 11):
    if i not in (3, 8):
        print(i, end=" ")


1 2 4 5 6 7 9 10 

In [2]:
# Question 02
for i in range(1, 101):
    if i % 7 == 0:
        print(i)
        break


7


In [6]:
# Question 03
s = "I am cool"
vowels = "aeiouAEIOU"

count = 0
for ch in s:
    if ch in vowels:
        count += 1

print("Number of vowels:", count)



Number of vowels: 4


In [4]:
# Question 04
for i in range(1, 31):
    if i % 5 != 0:
        print(i, end=" ")


1 2 3 4 6 7 8 9 11 12 13 14 16 17 18 19 21 22 23 24 26 27 28 29 

In [ ]:
# Question 05         Doubt in this question
for i in range (1,51):
    if i % 3==0:
        continue 
    if i == 40:
        break
print(i,end=" ")


40 

In [7]:
# Question 06
t = (1,2,2,3,4,4,5)
print(tuple(set(t)))


(1, 2, 3, 4, 5)


In [8]:
# Question 07
s = [10, 20, 4, 45, 99]
max1 = max(s)
s.remove(max1)
print(max(s))


45


In [9]:
# Question 08
s = [1,2,3,4,5,6]
mid = len(s)//2
print(s[:mid], s[mid:])


[1, 2, 3] [4, 5, 6]


In [10]:
# Question 09
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

common = []
for x in list1:
    if x in list2:
        common.append(x)

print(common)


[3, 4, 5]


In [11]:
# Question 10
s = [1,2,3,2,1]
print(s == s[::-1])


True


In [13]:
# Question 11
s = "Sneha"
freq = {}
for ch in s:
    freq[ch] = freq.get(ch, 0) + 1
print(freq)


{'S': 1, 'n': 1, 'e': 1, 'h': 1, 'a': 1}


In [ ]:
# Question 12
s = "programming"
dups = {ch for ch in s if s.count(ch) > 1}
print(dups)


In [16]:
# Question 13
s = "Vaibhav"
result = ""
for ch in s:
    if ch not in result:
        result += ch
print(result)


Vaibhv


In [23]:
# Question 14
s = "Beautiful"
vowels = "aeiouAEIOU"

result = ""
for ch in s:
    if ch in vowels:
        result += "*"
    else:
        result += ch

print(result)


B***t*f*l


In [24]:
# Question 15
s = "Love to watch movie"
count = len(s.split())

print("Number of words:", count)


Number of words: 4


# EDA PRACTICE QUESTION (07-02-2026)

In [25]:
# Question 01
import numpy as np

arr = np.arange(1, 11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
# Question 02
arr = np.zeros((3, 4))
print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
# Question 03
arr = np.linspace(0, 1, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [28]:
# Question 04
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Data type:", arr.dtype)
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)

Data type: int64
Shape: (2, 3)
Dimension: 2


In [29]:
# Question 05
s = [1, 2, 3, 4]
arr = np.array(s)
print(arr)

[1 2 3 4]


In [30]:
# Question 06
arr = np.array([1, 2, 3, 4])
arr = arr.astype(float)
print(arr)
print("Data type:", arr.dtype)


[1. 2. 3. 4.]
Data type: float64


In [31]:
# Question 07
arr = np.eye(4)
print(arr)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [32]:
# Question 08
arr = np.random.rand(5)
print(arr)


[0.35354267 0.05769471 0.55871171 0.8262073  0.36170515]


In [33]:
# Question 09
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])


30


In [34]:
# Question 10
import numpy as np
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
print(arr[1,2])

60


In [35]:
# Question 11
arr=np.array([1,2,3,4,5,6,7,8,9,10])
s=arr[arr % 2==0]
print(s)

[ 2  4  6  8 10]


In [36]:
# Question 12
arr=np.array([1,2,3,4,5])
rev=arr[::-1]
print(rev)

[5 4 3 2 1]


In [37]:
# Question 13
arr=np.array([12,15,6,16,3])
print("Maximum value:",np.max(arr))
print("Minimum value:",np.min(arr))

Maximum value: 16
Minimum value: 3


In [39]:
# Question 14
arr=np.array([5,12,8,15,16,10,20,7])
arr[arr>10]=10
print(arr)

[ 5 10  8 10 10 10 10  7]


In [40]:
# Question 15
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
e=arr1+arr2
print(e)

[ 6  8 10 12]


In [41]:
# Question 16
arr=np.array([1,2,3,4,5])
result=arr*5
print(result)

[ 5 10 15 20 25]


In [42]:
# Question 17
arr=np.arange(1,13)
s=arr.reshape(3,4)
print(s)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [43]:
# Question 18
arr=np.array([[1,2,3],
              [4,5,6]])
s=arr.flatten()
print(s)

[1 2 3 4 5 6]


In [ ]:
# Question 19
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
s=np.sum(arr, axis=1)           # (axis=1 row wise)
print(s)

[ 6 15 24]


In [ ]:
# Question 20
arr=np.array([[10,20,30],
              [40,50,60],
              [70,80,90]])
s=np.mean(arr,axis=0)             # (axis=0 column wise)
print(s)

[40. 50. 60.]
